#!/usr/bin/env ruby
# frozen_string_literal: true

require 'gli'
# Overall Gitkeep module
module Gitkeep
  # CLI module - required for GLI
  module CLI
    include GLI::App
    extend self

    program_desc 'gitkeep - a tool for managing git and github'
    subcommand_option_handling :normal
    arguments :strict

    require_relative 'lib/gitkeep'

    exit run(ARGV)
  end
end
